# Zooplankton

## Contributors

## Overview

The approach to simulate zooplankton biomass is similar to the previous chapter on simulating algal biomass. Multiple zooplankton functional groups can be simulated, where each group is parameterized according to the taxonomic group of interest (e.g., cladocerans, copepods, and rotifers). Groups can also be used to model several unique species, or different size classes of a single species. Similar to the phytoplankton module, zooplankton functional groups are unique, yet share a similar mathematical approach to simulate grazing, respiration, predation, mortality, excretion, and egestion.

## Model Description

The main balance equation for a single zooplankton functional group, $ZOO_a$, is described as:

### Process Descriptions

#### Grazing

The rate of removal of phytoplankton from the water due to grazing by these groups is determined using the following model. Each zooplankton group, $z$, has a grazing preference for a particular phytoplankton group $a$, denoted by $P_{za}$, $P_{zz}$ for zooplankton grazing on other zooplankton, and for detrital material (POM), denoted by $P_{zd}$. The weighted grazing function, $f^{ZGW}$, by zooplankton group $z$ on each of the phytoplankton groups $a$ is therefore denoted by:

\begin{equation}
f_{A_a}^{ZGW}\left(Z_z,A_a\right) =
\frac{P_{za}\:A_a\:Y_{C:Chla_a}}{\sum_{a}^{N_A}[P_{za}\:A_a\:Y_{C:Chla_a}] +\sum_{k}^{N_Z}[P_{zk}\:Z_k]+\sum_{d}^{N_D}[P_{zd}\:POC_d]}
\end{equation}

where $A_a$ is the chlorophyll-a ($\mu g$ $Chla$ $L^{-1}$) associated with each phytoplankton group $a$, $Z_z$ is the biomass of zooplankton group $z$ as $mg$ $C$ $L^{-1}$, $Y_{C:Chla}$ is the mass of carbon ($mg$) to chlorophyll-a($\mu g$) in phytoplankton, $N_D$ is the number of detrital groups. Appropriate choice of parameters in this expression (i.e. setting grazing preferences solely to phytoplankton by setting the remaining grazing preferences to zero) will limit grazing by zooplankton to phytoplankton.

The grazing function, $f^{GRZ}$, is used to describe the rate of removal of phytoplankton group $a$ due to grazing by all zooplankton groups is thus:

\begin{equation}
f_{A_a}^{GRZ_X}\left(Z,0,A_a\right)=\sum_{z}^{N_Z}G_X\left(Z_z\right)f^{ZGW}_{A_a}\left(Z_z,g\right)
\end{equation}

where $X$ is the nutrient of interest: $C$, $N$ or $P$. The above formula sums over each zooplankton group $z$ in order to determine the total removal of phytoplankton group $a$; $f_{A_a}^{GRZ}$ has units of $mg$ $Chla$ $L^{-1}$ $day^{-1}$. For more detail on the estimation of $G$, see Section \ref{zooplankton}).

Zooplankton graze on phytoplankton (which may be simulated with or without dynamically calculated internal nutrient supplies), detritus (made up of particulate carbon, nitrogen and phosphorus, bacteria, and on other zooplankton. Grazing preferences are assigned to each food source ($A$, $Z$, $POCL$, $POCR$ & $B$), and the overall potential rate of carbon consumption is regulated by a Michaelis-Menten function, $f_{Z_z}^{ZFD}$ for available food supply:

\begin{equation}
f_{Z_z}^{ZFD}(A,Z,B,POC)= \frac{\sum_{a}^{N_A}A_aY_{C:Chla_a}+\sum_{k}^{N_Z}Z_k+\sum_{d}^{N_D}POC_d+B}{ K_{Z_z}+\sum_{a}^{N_A}A_aY_{C:Chla_a}+\sum_{k}^{N_Z}Z_z+\sum_{d}^{N_D}POC_d+B}
\end{equation}

where $K_{Z_z}$ is the half-saturation constant for the effect of food abundance on grazing. Each zooplankton group, $z$, has a grazing preference for a particular phytoplankton group $a$, denoted by $P_{za}$, $P_{zk}$ for zooplankton grazing on other zooplankton, and for detrital material (POM), denoted by $P_{zd}$. Therefore, we can calculate the total amount of carbon grazed, $G$, from:

\begin{equation}
G_C\left(Z_z\right) = g_{MAX_z}\:f_{Z_z}^{T1}(T)\:f_{Z_z}^{ZFD}(A,Z,B,POC) Z_z
\end{equation}

where $g_{MAX}$ is the grazing rate coefficient ($mg$ consumed $C$ ($mg$ zooplankton $C$)$^{-1}$ $day^{-1}$), and $f_{Z_z}^{T1}(T)$ is a function for temperature dependence of grazing (refer to phytoplankton temperature sub-section for information on $f^{T1}$). Nutrient accumulation through grazing is more complicated since the sources may have different nutrient concentrations. A grazing function for nutrients is therefore requires knowledge of the relative contribution of each food source, defined using a weighting function:

\begin{equation}
f_{Y}^{ZGW}\left(Z_z,Y\right) =
\frac{P_{zy}Y}{\sum_{a}^{N_A}[P_{za}\:A_a\:Y_{C:Chla_a}] +\sum_{k}^{N_Z}[P_{zk}\:Z_k]+\sum_{d}^{N_D}[P_{zd}\:POC_d]}\label{eq:ZW}
\end{equation}

where $y$ is a generic group index and $Y$ is the substance of concern(i.e. $A_a$, $Z_z$, $POC_d$ or $B$ in carbon units). Using this weighting function, the nitrogen consumption is modelled as:

\begin{eqnarray}
G_N\left(Z_z\right) &=& \underbrace{\sum_{a}^{N_A}G_C(Z_z)f_{A_a}^{ZGW}(Z_z,A_a)\frac{AIN_a}{A_a}P_{za}}_{\text{a-N from phytoplankton}} + \underbrace{\sum_{k}^{N_Z}G_C(Z_z)f_{Z_k}^{ZGW}(Z_z,Z_k)k_{ZIN_k}P_{zk}}_{\text{a-N from zooplankton}} \nonumber \\ &+&
\underbrace{G_C(Z_z)f_{B}^{ZGW}(Z_z,B)k_{BIN}P_{zb}}_{\text{a-N from bacteria}} +
\underbrace{\sum_{d}^{N_D}G_C(Z_z)f_{POC_d}^{ZGW}(Z_z,POC_d)\frac{PON_d}{POC_d}P_{zd}}_{\text{a-N from POM}}
\end{eqnarray}

where $k_{ZIN_z}$ is the user-defined internal nitrogen concentration ($mg$ $N$ ($mg$ $C$)$^{-1}$) of the $z^{th}$ zooplankton being consumed and $AIN_a$ is the internal algal $N$ concentration (see Section \ref{phytoplankton}). Similarly, the phosphorus intake equation is written as:

\begin{eqnarray}
G_P\left(Z_z\right) &=& \underbrace{\sum_{a}^{N_A}G_C(Z_z)f_{A_a}^{ZGW}(Z_z,A_a)\frac{AIP_a}{A_a}P_{za}}_{\text{a-P from phytoplankton}} + \underbrace{\sum_{k}^{N_Z}G_C(Z_z)f_{Z_k}^{ZGW}(Z_z,Z_k)k_{ZIP_k}P_{zk}}_{\text{a-P from zooplankton}} \nonumber \\ &+&
\underbrace{G_C(Z_z)f_{B}^{ZGW}(Z_z,B)k_{BIP}P_{zb}}_{\text{a-P from bacteria}} +
\underbrace{\sum_{d}^{N_D}G_C(Z_z)f_{POC_d}^{ZGW}(Z_z,POC_d)\frac{POP_d}{POC_d}P_{zd}}_{\text{a-P from POM}}
\end{eqnarray}

where $k_{ZIP_z}$ is the user-defined internal phosphorus concentration ($mg$ $P$ ($mg$ $C$)$^{-1}$) for the $z^{th}$ zooplankton being consumed and and $AIP_a$ is the internal algal $P$ concentration (see Section \ref{phytoplankton}).

#### Predation

It is assumed in the model that consumption by fish is a major zooplankton loss from the water column. To model fish grazing, a weighted preference is first assigned to each zooplankton group:

\begin{equation}
f_{Z_z}^{FGW}\left(F_f,Z_z\right) =
\frac{P_{fz}\:Z_z}{\sum_{a}^{N_A}[P_{fa}\:A_a\:Y_{C:Chla_a}] +\sum_{k}^{N_Z}[P_{fk}\:Z_k]+\sum_{d}^{N_D}[P_{fd}\:POC_d]}
\end{equation}

where $P_{fz}$ is the preference of fish group $f$ on zooplankton group $z$ relative to the total composition of their diet.

For grazing by other zooplankton, a weighted preference is allocated to each zooplankton group according to \ref{eq:ZW}.

Therefore the total loss of zooplankton through grazing by fish and other zooplankton is given by:

\begin{equation}
f_{Z_z}^{GRZ_X}\left(Z,F,Z_z\right)=\sum_{k}^{N_Z}G_X\left(Z_z\right)f^{ZGW}_{Z_z}\left(Z_z,Z_k\right)+\sum_{f}^{N_F}G_X\left(F_f\right)f^{FGW}_{Z_z}\left(F_f,Z_z\right)
\end{equation}

where $X$ is the nutrient of interest: $C$, $N$ or $P$. The above formula sums over each zooplankton group $k$, and each fish group, $f$, in order to determine the total removal of zooplankton group $z$. For more detail on the estimation of $G$ by the fish, see Section \ref{fish}).

#### Respiration

Respiration is modelled by using a respiration rate coefficient, $k_{zR_z}$ for each zooplankton class, $z$, and assigning the usual temperature dependence:

\begin{equation}
R_{DIC}(Z_z) = k_{zR_z}\vartheta^{T-20}\:Z_z.
\end{equation}

The carbon lost to $CO_2$ is used to increment the $DIC$ concentration if $DIC$ is being simulated, and the equivalent mass of $O_2$ is also consumed. No nutrients are lost through respiration.

#### Mortality, Excretion, and Egestion

Zooplankton losses through mortality, excretion and egestion (i.e. faecal pellets) are modelled according to:

\begin{eqnarray}
E_{DOCL}(Z_z) &=& \underbrace{k_{zE_z}\:G_C(Z_z)}_{\text{excretion}} \\
E_{POCL}(Z_z) &=& \underbrace{k_{zF_z}\:G_C(Z_z)}_{\text{faecal pellets}} + \underbrace{k_{zM_z}\vartheta^{T-20}\:Z_z}_{\text{mortality}}
\end{eqnarray}

where $k_{zE_z}$ and $k_{zF_z}$ are fractions of the grazed food that are lost to excretion and faecal pellets respectively, and $k_{zM_z}$ is the mortality rate coefficient ($day^{-1}$).

The nutrient loss due to mortality contributes to (labile) particulate $N$ and $P$, and because zooplankton internal nutrient ratios are fixed, the nutrient loss due to mortality is expressed as the amount of carbon lost to mortality multiplied by the zooplankton internal nutrient concentration ($k_{ZIN_z}$ and $k_{ZIP_z}$). For nutrient loss via faecal pellets, the nutrient concentration is assumed not be the zooplankton internal nutrient concentration, but the mean nutrient concentration of all the grazed food. Therefore, the loss of nutrients from the zooplankton pool to particulate detritus is calculated from:

\begin{eqnarray}
E_{PONL}(Z_z) &=& \underbrace{k_{zF_z}\:G_N(Z_z)}_{\text{faecal pellets}} + \underbrace{k_{zM_z}\vartheta^{T-20}\:k_{ZIN_z}\:Z_z}_{\text{mortality}}
\end{eqnarray} for nitrogen, and: \begin{eqnarray}
E_{POPL}(Z_z) &=& \underbrace{k_{zF_z}\:G_P(Z_z)}_{\text{faecal pellets}} + \underbrace{k_{zM_z}\vartheta^{T-20}\:k_{ZIP_z}\:Z_z}_{\text{mortality}}
\end{eqnarray}

for phosphorus. The loss of nutrients via excretion to the dissolved organic pool however, is more complicated as this term is used to maintain the user-defined constant internal nutrient ratio within the zooplankton. Therefore, each of the processes described above are performed first and stored in an auxiliary/buffer(\*) array, and then any excess N or P is removed. In the case of a nutrient limited system, excess carbon must also be removed. There are therefore 4 possible scenarios: both N and P are in excess, P is limiting, N is limiting or both N and P is limiting. For the first case it is simply a matter of removing the excess nutrients to maintain the internal ratio:

\begin{eqnarray}
E_{DONL}(Z_z) &=& \frac{ZIN_{z}^{*}-Z_{z}^{t+1}\:k_{ZIN_z}}{\Delta t}
\label{eq:zn}
\end{eqnarray} for nitrogen, and: \begin{eqnarray}
E_{DOPL}(Z_z) &=& \frac{ZIP_{z}^{*}-Z_{z}^{t+1}\:k_{ZIP_z}}{\Delta t}
\label{eq:zp}
\end{eqnarray}

for phosphorus, where $ZIN$ and $ZIP$ are concentrations of zooplankton internal nitrogen and phosphorus respectively, the $^*$ indicates that value has already been update by grazing, mortality and egestion, $Z_{z}^{t+1}$ is the zooplankton concentration at the forward timestep (i.e. after it has been updated with the carbon fluxes previously described in this section). For the case where phosphorus is limiting (i.e. insufficient phosphorus uptake to maintain internal homeostasis), then some extra carbon must be excreted (as $DOCL$). The nitrogen excreted is then same as for \ref{eq:zn}, but using the incremented carbon concentration, and $E_{DOPL}=0$. For the case where nitrogen is limiting (i.e. insufficient nitrogen uptake to maintain internal homeostasis), then some extra carbon must be excreted (as $DOCL$). The phosphorus excreted is then same as for \ref{eq:zp}, but using the incremented carbon concentration, and $E_{DONL}=0$. If both N and P are limiting, $DOCL$ is excreted until the $k_{ZIN}$ and $k_{ZIP}$ are satisfied.

<!-- ### Variable Summary -->

<!-- ### Parameter Summary -->

<!-- ### Optional Module Links -->

<!-- ### Feedbacks to the Host Model -->

<!-- ## Setup & Configuration -->

<!-- ## Case Studies & Examples -->

<!-- ### Case Study -->

<!-- ### Publications -->
